#!/bin/bash

COMMAND={{platform_bin_dir}}/riak
RUNNER_LOG_DIR={{platform_log_dir}}

case "$1" in
	start|console|foreground)
		su - riak -c "RUNNER_LOG_DIR=${RUNNER_LOG_DIR} PIPE_DIR=${PIPE_DIR} ${COMMAND} ${*} -pa {{platform_lib_dir}}/patches"
		;;
	*)
		su - riak -c "RUNNER_LOG_DIR=${RUNNER_LOG_DIR} PIPE_DIR=${PIPE_DIR} ${COMMAND} ${*}"
		;;
esac
