#!/bin/bash

COMMAND={{platform_bin_dir}}/riak
RUNNER_LOG_DIR={{platform_log_dir}}
RUNNER_GEN_DIR="${RUNNER_GEN_DIR:-{{ platform_gen_dir }}}"
RELEASE_ROOT_DIR="${RELEASE_ROOT_DIR:-{{ runner_base_dir }}}"

if [ -e "$RUNNER_GEN_DIR/vm.args" ]; then
    ln -sf $RUNNER_GEN_DIR/vm.args $RELEASE_ROOT_DIR/vm.args
fi

if [ -e "$RUNNER_GEN_DIR/sys.config" ]; then
    ln -sf $RUNNER_GEN_DIR/sys.config $RELEASE_ROOT_DIR/sys.config
fi

if [[ $EUID -ne 0 ]]; then
   echo "You need to be root or use sudo to run this command." 
   exit 1
fi

case "$1" in
	start|console|foreground)
		su - riak -c "RUNNER_LOG_DIR=${RUNNER_LOG_DIR} PIPE_DIR=${PIPE_DIR} ${COMMAND} ${*} -pa {{platform_lib_dir}}/patches"
		;;
	*)
		su - riak -c "RUNNER_LOG_DIR=${RUNNER_LOG_DIR} PIPE_DIR=${PIPE_DIR} ${COMMAND} ${*}"
		;;
esac
